# Generated by Django 4.0.3 on 2022-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanye_quote', models.TextField(null=True, unique=True, verbose_name='Цитата Kanye')),
                ('letters_amount', models.IntegerField(null=True, verbose_name='Количество букв в цитате')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
