# Generated by Django 4.0.3 on 2022-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ten_quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='consonants',
            field=models.IntegerField(null=True, verbose_name='Количество согласных'),
        ),
        migrations.AddField(
            model_name='quote',
            name='vowels',
            field=models.IntegerField(null=True, verbose_name='Количество гласных'),
        ),
    ]
