# Generated by Django 4.0.3 on 2022-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ten_quotes', '0002_quote_consonants_quote_vowels'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='repeated_letters',
            field=models.TextField(null=True, verbose_name='Количество появлений каждой буквы'),
        ),
    ]
